name: darvester
description: Powerful Discord OSINT Toolkit
publish_to: 'none'
version: 2.0.0-alpha.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  go_router: ^6.0.1
  sqflite:
  shared_preferences:
  file_picker: ^5.2.5
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  intl:
  lazy_load_scrollview:
  cached_network_image:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: Unbounded
      fonts:
        - asset: fonts/Unbounded-Regular.ttf
    - family: UnboundedLight
      fonts:
        - asset: fonts/Unbounded-Light.ttf
    - family: UnboundedBold
      fonts:
        - asset: fonts/Unbounded-Bold.ttf
  assets:
    - images/default_avatar.png
    - images/transparent.png

  uses-material-design: true
